import type { Metadata } from 'next';
import { Toaster } from 'react-hot-toast';

import './globals.css';
import Sidebar from '@/components/Sidebar';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className='flex min-h-screen font-sans'>
        <Sidebar />
        <main className='flex-1 bg-gray-100 p-6 overflow-y-auto'>
          {children}
        </main>
        <Toaster position='top-right' reverseOrder={false} />
      </body>
    </html>
  );
}
