import type { Metadata } from 'next';
import { FaHome, FaPlus } from 'react-icons/fa';

import Link from 'next/link';

import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const navItems = [
  {
    label: 'List Applications',
    icon: <FaHome />,
    href: '/',
  },
  {
    label: 'Create Application',
    icon: <FaPlus />,
    href: '/apply',
  },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname =
    typeof window !== 'undefined' ? window.location.pathname : '/';

  return (
    <html lang='en'>
      <body className='flex min-h-screen font-sans'>
        {/* Sidebar */}
        <aside className='w-64 bg-gray-900 text-white flex flex-col px-6 py-8'>
          <h2 className='text-2xl font-bold mb-10 text-blue-400 tracking-wide'>
            MortgageApp
          </h2>

          <nav className='space-y-3 text-sm flex-1'>
            {navItems.map((item) => (
              <Link
                key={item.href}
                href={item.href}
                className={`flex items-center gap-3 px-4 py-3 rounded-lg transition-colors
                  ${
                    pathname === item.href
                      ? 'bg-blue-600 text-white'
                      : 'hover:bg-gray-700 text-gray-300'
                  }`}
              >
                <span className='text-lg'>{item.icon}</span>
                {item.label}
              </Link>
            ))}
          </nav>

          <footer className='mt-auto text-xs text-gray-500'>
            &copy; {new Date().getFullYear()} Mortgage System
          </footer>
        </aside>

        {/* Main content */}
        <main className='flex-1 bg-gray-100 p-6 overflow-y-auto'>
          {children}
        </main>
      </body>
    </html>
  );
}
